### ISSUE TITLE
different version in metadata: '0.0.0'

### ISSUE THREAD

**Issue by ellie-narducci** [hiroaki-yamamoto/django-good-otp#197]
when running pip install, I get this error. Has anything happened to the metadata in recent commits?
<img width="974" alt="Screen Shot 2021-03-09 at 8 58 08 am" src="https://user-images.githubusercontent.com/77259048/110403594-5696e700-80b8-11eb-9447-cf8fad019994.png">

**Comment by hiroaki-yamamoto** [comment]
@ellie-narducci Could you try 1.2.2? If it doesn't working, re-open this issue :pray:
